/*export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGOUT_START = 'LOGOUT_START';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';*/

export const CATEGORYEXP_LOAD_START = 'CATEGORYEXP_LOAD_START';
export const CATEGORYEXP_LOAD_SUCCESS = 'CATEGORYEXP_LOAD_SUCCESS';
export const CATEGORYEXP_LOAD_ERROR = 'CATEGORYEXP_LOAD_ERROR';

export const SAVINGS_LOAD_START = 'SAVINGS_LOAD_START';
export const SAVINGS_LOAD_SUCCESS = 'SAVINGS_LOAD_SUCCESS';
export const SAVINGS_LOAD_ERROR = 'SAVINGS_LOAD_ERROR';

export const HOME_START = 'HOME_START';
export const HOME_SUCCESS = 'HOME_SUCCESS';
export const HOME_ERROR = 'HOME_ERROR';

export const CATEGORYSAV_LOAD_START = 'CATEGORYSAV_LOAD_START';
export const CATEGORYSAV_LOAD_SUCCESS = 'CATEGORYSAV_LOAD_SUCCESS';
export const CATEGORYSAV_LOAD_ERROR = 'CATEGORYSAV_LOAD_ERROR';

export const CATEGORYEXP_PAGE_LOAD_START = 'CATEGORYEXP_PAGE_LOAD_START';
export const CATEGORYEXP_PAGE_LOAD_SUCCESS = 'CATEGORYEXP_PAGE_LOAD_SUCCESS';
export const CATEGORYEXP_PAGE_LOAD_ERROR = 'CATEGORYEXP_PAGE_LOAD_ERROR';

export const USER_START = 'USER_START';
export const USER_SUCCESS = 'USER_SUCCESS';
export const USER_ERROR = 'USER_ERROR';
export const USER_POST_SUCCESS = 'USER_POST_SUCCESS';

export const USER_INFO_START = 'USER_INFO_START';
export const USER_INFO_SUCCESS = 'USER_INFO_SUCCESS';
export const USER_INFO_ERROR = 'USER_INFO_ERROR';

export const ADMIN_PAGE_START = 'ADMIN_PAGE_START';
export const ADMIN_PAGE_SUCCESS = 'ADMIN_PAGE_SUCCESS';
export const ADMIN_PAGE_ERROR = 'ADMIN_PAGE_ERROR';

export const ADMIN_PAGE_CONFIRM_SAV_SUM_START = 'ADMIN_PAGE_CONFIRM_SAV_SUM_START';
export const ADMIN_PAGE_CONFIRM_SAV_SUM_SUCCESS = 'ADMIN_PAGE_CONFIRM_SAV_SUM_SUCCESS';
export const ADMIN_PAGE_CONFIRM_SAV_SUM_ERROR = 'ADMIN_PAGE_CONFIRM_SAV_SUM_ERROR';

export const ADMIN_PAGE_CONFIRM_DEL_SAV_START = 'ADMIN_PAGE_CONFIRM_DEL_SAV_START';
export const ADMIN_PAGE_CONFIRM_DEL_SAV_SUCCESS = 'ADMIN_PAGE_CONFIRM_DEL_SAV_SUCCESS';
export const ADMIN_PAGE_CONFIRM_DEL_SAV_ERROR = 'ADMIN_PAGE_CONFIRM_DEL_SAV_ERROR';

export const TEST_START = 'TEST_START';
export const TEST_SUCCESS = 'TEST_SUCCESS';
export const TEST_POST_SUCCESS = 'TEST_POST_SUCCESS';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';